### PR TITLE
fix test help text to indicate verbosity 4 is an option

### PR DESCRIPTION
**Pull request by wilsoncusack**
Verbosity 4 is now an option, includes traces even when tests pass.

### CODE REVIEW

**Comment by brockelmore** [comment]
max is 5 :) 
3: if fail, print test trace
4: regardless of status, print test trace, if failed test print setup
5: regardless of status, print setup trace and test trace

**Comment by wilsoncusack** [comment]
Lol, I actually thought it was missing setup but then got distracted. 

Let's take verbosity to 11!!

**Comment by gakonst** [comment]
Should we maybe reduce verbosity levels? 0-5 seems like a lot. Feels like we could do with `-v` `-vv` and `-vvv` @brockelmore?

**Comment by gakonst** [comment]
@wilsoncusack To get this PR over the line let's replace the doc comment here with what brock described?

**Comment by wilsoncusack** [comment]
Sure! @brockelmore how should we describe < 3

**Comment by gakonst** [comment]
Superseded by https://github.com/gakonst/foundry/pull/376

**Pull request closed without merging**
