### PR TITLE
REVM fuzzer

### LINKED ISSUE #754: Fuzzing
Re-adding fuzzing to the new REVM backend

### PR DESCRIPTION
**Pull request by onbjerg**
Ports the fuzzer from `evm-adapters` over to REVM, as well as some tests from `evm-adapters`. Finally, re-enables tests for the runner and multi-runner.

Note that one of the tests for `MultiRunnerContractBuilder` is failing - it's a library linking test I don't think we were running before. It doesn't seem like it is supposed to fail, but I couldn't figure out why it was. Are we having lib linking issues? :thinking: 

The fuzz tests currently lack the `vm.assume` cheatcode (since cheatcodes are not ported) and traces (since traces are not ported).

I also moved `fuzz_param` and `fuzz_calldata` into a strategies module (which `evm-adapter` also had, just only with a uint strategy)

Closes #754

### CODE REVIEW

**Comment by gakonst** [comment]
The test which fails is [this](https://github.com/gakonst/foundry/blob/onbjerg/revm-fuzz/forge/testdata/LibLinking.sol#L62) one during nested calls

**Comment by gakonst** [comment]
> Note that one of the tests for MultiRunnerContractBuilder is failing - it's a library linking test I don't think we were running before. It doesn't seem like it is supposed to fail, but I couldn't figure out why it was. Are we having lib linking issues? 🤔

This is [this](https://github.com/gakonst/foundry/blob/onbjerg/revm-fuzz/forge/testdata/LibLinking.sol#L62) test, which has nested linking. Wonder if it's a REVM bug?

**Comment by onbjerg** [comment]
I figured it out - the nonce was incorrectly set (see #446) which deployed the libraries at an incorrect address

**Review by gakonst — APPROVED** [review]
LGTM don't forget to fmt

**Pull request merged**
