### PR TITLE
feat(evm-cheatcodes): MINOR/AESTHETIC: Alias `prank(address)` to `spoof(address)`

### PR DESCRIPTION
**Pull request by dmfxyz**
## Motivation
Semantically (in English, so there is a bias), `spoof` more closely defines the behavior and actions that `prank` accomplishes. Think of phone-number spoofing or email spoofing. `prank` is really spoofing the msg.sender (rather than "pranking" it).

## Solution

This PR exposes a new cheatcode accessed via `spoof` that still calls the underlying `prank` implementation for simplicity and backwards compatibility. 

Tests coming, just drafting for visibility.

### CODE REVIEW

**Comment by mds1** [comment]
Personally I would prefer not to merge this PR for the following reasons:
- The name `prank` comes from a prank phone call, so here you are making a prank `CALL` in the EVM. Therefore it does define the behavior of the action, though perhaps that logic should be documented better for clarity
- We'd also need to add `startSpoof`, and `stopSpoof` for consistency, which means adding 3 redundant cheat codes which clutters the cheat code interface

**Comment by dmfxyz** [comment]
> Personally I would prefer not to merge this PR for the following reasons:
> 
> * The name `prank` comes from a prank phone call, so here you are making a prank `CALL` in the EVM. Therefore it does define the behavior of the action, though perhaps that logic should be documented better for clarity
> * We'd also need to add `startSpoof`, and `stopSpoof` for consistency, which means adding 3 redundant cheat codes which clutters the cheat code interface

@mds1 I definitely see your point around cluttering the cheat code interface. I was planning to add the `startSpoof` and `stopSpoof` this evening. It's not ideal, especially if/when more cheat codes are added in the future.

While I love the prank call analogy, I personally still find it somewhat unclear for a couple of reasons:
- The signature `prank(address)` semantically suggests that you are making a prank call to that address, but in fact you are using that address to prank call another address. This was actually the original source of my confusion (I thought I should be calling prank() on the address that I wanted to prank call, so to speak).
 
- While you are making a prank call in the EVM, the cheat is invoked in the context of a test. So I think its name should more closely describe what it's doing at the test contract level (imitating an address sender) than what it's doing under the hood (literally performing a prank `CALL`). 

Of course this is a pretty subjective argument. The idea spawned from a hackathon over this weekend where number of us were confused by naming, but clearly we figured it out quickly enough (by actually re-reading the nested Cheat Code documentation 😄 ). Happy to abandon if others think it's too much overhead, or at worse even more confusing.

**Comment by tynes** [comment]
I generally think that having one canonical way to do things is better than multiple ways to do things as its more socially scalable

**Comment by onbjerg** [comment]
This can be done in userland, i.e. write a method called `spoof` that calls `prank`. For that reason (+ maintainability in not having aliases) I will close this. cc @gakonst @mattsse as well if they have any objections. :smile:

**Comment by dmfxyz** [comment]
> This can be done in userland, i.e. write a method called `spoof` that calls `prank`. For that reason (+ maintainability in not having aliases) I will close this. cc @gakonst @mattsse as well if they have any objections. 😄

Makes sense!

**Comment by gakonst** [comment]
I agree with all comments above - thanks for the work / understanding @dmfxyz! Aliasing makes sense here at a separate contract

**Pull request closed without merging**
