### PR TITLE
Don't suppress warnings

### PR DESCRIPTION
**Pull request by onbjerg**
Fixes https://github.com/gakonst/foundry/issues/304

image

### CODE REVIEW

**Comment by gakonst** [comment]
We should probably add `ignored_error_codes` (impl [here](https://github.com/gakonst/ethers-rs/blob/86044bc0c328bb0d7f420dbebd587b556bcb90f5/ethers-solc/src/lib.rs#L505-L506)) to the CLI. perhaps we should by default ignore error codes corresponding to the 24kb limit?

**Comment by mds1** [comment]
> perhaps we should by default ignore error codes corresponding to the 24kb limit?

Only for test contracts though. My preference for the defaults would be:
- ignore size limit error code for [test contracts](https://github.com/dapphub/ds-test/blob/0a5da56b0d65960e6a994d2ec8245e6edd38c248/src/test.sol#L38)
- ignore SPDX license identifier warnings for test contracts and dependencies

**Comment by mattsse** [comment]
this seems to be something you should be able to configure, so I'll add an option to the config #297 
like `ignored-error-codes = [1,2,3,4]`

**Comment by onbjerg** [comment]
I'm not entirely sure how I should go about differentiating between tests/non-tests for error codes we want to ignore. I suppose I would need to somewhat rework `ethers-solc` to ignore error codes based on type and then we would need to filter based on file names (from `Error::source_location` [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/artifacts.rs#L1488)), making the assumption that test names end in `.t.sol`? Or am I missing something? :thinking:

**Comment by gakonst** [comment]
We assume a test file is any file that has a function that starts with the word `test`. That might be enough.

This might be too wide, so other filters you could use are:
* if there's the DsTest [`IS_TEST`](https://github.com/dapphub/ds-test/blob/master/src/test.sol#L38) variable  in the ABI,
* if the files ends in `.t.sol`

**Comment by gakonst** [comment]
I cannot seem to find a list of error code -> expected string error, doing a Github search I sense you can find it at the places where ["errorReporter warning"](https://github.com/ethereum/solidity/search?p=2&q=errorReporter+warning&type=) is referenced

**Comment by onbjerg** [comment]
Yeah I couldn't find one either. It looks like the error IDs are autogenerated and dispersed all over the place :/ 

https://github.com/ethereum/solidity/blob/8569cf32f6e0cf2e9b341a085a3bae84e5c451c4/liblangutil/Exceptions.h#L149-L164

**Review by gakonst — APPROVED** [review]

**Pull request merged**
