### PR TITLE
fix: fuzzer handles int/uint size generation correctly

### PR DESCRIPTION
**Pull request by mds1**
Closes https://github.com/gakonst/foundry/issues/341 by always generating a U256 and wrapping to the desired size

Question—How can I verify the values being output by the strategy are in the expected range? I did some spot checks with solidity tests but not sure how to get more insight

Also, one thing that's a bit annoying (but I think can be handled in a separate issue) is if you write a test like the below:

```solidity
function testLimits(int40 a) public {
    assertGe(a, 0);
  }
```

you get a failure case like this, where I'd expect the int to be shown as a negative value instead of a uint as currently shown:

`[FAIL. Reason: . Counterexample: calldata=0x4db19789ffffffffffffffffffffffffffffffffffffffffffffffffffffff8000000000, args=[Int(115792089237316195423570985008687907853269984665640564039457584007363373826048)]]`

### CODE REVIEW

**Comment by gakonst** [comment]
You can run the command with `RUST_LOG=forge=trace=evm_adapters=trace` in the env vars, and it'll proceed to print all the values it checks. I would probably grep the values and plot the distribution.

**Comment by mds1** [comment]
Values look good, so aside from any code suggestions this PR should be ready

Worth noting rejection sampling isn't a good alternative to the modulo approach used here because of how large the number ranges are, so you end up rejecting the vast majority of inputs

**Comment by mds1** [comment]
Some benchmarks using the below tests:

```solidity
function test_limits(uint40 a) public {
    assertLe(a, type(uint40).max);
    assertGe(a, 0);
  }

  function test_limits2(int40 a) public {
    assertLe(a, type(int40).max);
    assertGe(a, type(int40).min);
  }
```

```sh
$ time PROPTEST_CASES=1000 ~/prj/foundry/target/debug/forge test -m "\btest_limits"
compiling...
no files changed, compilation skippped.
Running 2 tests for "Constructor.json":Constructor
[PASS] test_limits(uint40) (runs: 1000, μ: 867, ~: 868)
[PASS] test_limits2(int40) (runs: 1000, μ: 984, ~: 1142)
PROPTEST_CASES=1000 ~/prj/foundry/target/debug/forge test -m "\btest_limits"  13.06s user 0.12s system 97% cpu 13.467 total

$ time PROPTEST_CASES=10000 ~/prj/foundry/target/debug/forge test -m "\btest_limits"
compiling...
no files changed, compilation skippped.
Running 2 tests for "Constructor.json":Constructor
[PASS] test_limits(uint40) (runs: 10000, μ: 867, ~: 868)
[PASS] test_limits2(int40) (runs: 10000, μ: 977, ~: 818)
PROPTEST_CASES=10000 ~/prj/foundry/target/debug/forge test -m "\btest_limits"  87.83s user 0.33s system 99% cpu 1:28.59 total

$ time PROPTEST_CASES=100000 ~/prj/foundry/target/debug/forge test -m "\btest_limits"
compiling...
no files changed, compilation skippped.
Running 2 tests for "Constructor.json":Constructor
[PASS] test_limits(uint40) (runs: 100000, μ: 867, ~: 868)
[PASS] test_limits2(int40) (runs: 100000, μ: 979, ~: 818)
PROPTEST_CASES=100000 ~/prj/foundry/target/debug/forge test -m "\btest_limits  851.03s user 2.25s system 99% cpu 14:16.12 total
```

**Review by gakonst — APPROVED** [review]
LGTM - we should: 1. add corner cases in a separate PR, 2. look into how we can unit test custom strategies

**Pull request merged**
