### PR TITLE
feat(forge): getNonce and setNonce cheatcodes

### LINKED ISSUE #554: feat: `getNonce` and `setNonce` cheatcodes
```solidity
interface Vm {
  // Gets the nonce required for the next transaction
  function getNonce(address) external;
  // Sets the next required nonce, where new nonce must be > current nonce
  function setNonce(address,uint256) external;
}
```

Use cases:
- Precompute addresses that should be emitted from logs in factory contracts, e.g. https://github.com/gakonst/foundry/issues/543
- Asserting an addresses nonce is what you'd expect, to facilitate deterministic deploys in https://github.com/gakonst/foundry/issues/402

### PR DESCRIPTION
**Pull request by calldata**
## Motivation

implement the setNonce/getNonce feature

closes #554

### CODE REVIEW

**Comment by calldata** [comment]
wait for https://github.com/rust-blockchain/evm/pull/92 to be merged

**Comment by gakonst** [comment]
@calldata https://github.com/rust-blockchain/evm/pull/92 is now merged!

**Comment by calldata** [comment]
@gakonst  where should i expose the `account_mut` function ?

**Comment by gakonst** [comment]
Sorry @calldata, my bad. We're now blocked on https://github.com/rust-blockchain/evm/pull/98. The thing I'd do is add a `pub fn account_mut(address: Address) -> ...` function on `MemoryStackOwned` which calls `self.substate.account_mut`

**Comment by gakonst** [comment]
@onbjerg worth adding to the PR for cheats, if easy to add. closing as it doesn't look like we're gonna get the sputnik PR merged anytime soon, and we'll address in the REVM transition

**Pull request closed without merging**
