### PR TITLE
ci: build arm64 linux nightlies

### LINKED ISSUE #684: Add aarch64 Linux to the nightly build
### Component

Foundryup

### Describe the feature you would like

Hey 👋 

Can we add the aarch64 Linux target to the nightly build? It would be nice so that me and other aarch64 Linux users won't need to rebuild from sources each time.

It should be just adding a few lines to [`release.yml`](https://github.com/gakonst/foundry/blob/63644de7dccb05a42f04f2829fd4007049607788/.github/workflows/release.yml).

Thanks!

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by onbjerg**
If I read `foundryup` correctly this should already be supported, so this is the only change needed, given Cargo doesn't complain

Closes #684

### CODE REVIEW

**Comment by onbjerg** [comment]
Should we add a warning to `foundryup` when installing on ARM platforms that Foundry only works with autodetection turned off, or should we just ship as-is given we're trying to land ARM support in svm-rs?

**Comment by gakonst** [comment]
I'd do:
1. Add a warning that "forge on arm has autodetection disabled. you can track progress in https://github.com/gakonst/foundry/issues/525"
2. I'd add a cfg target = arm [here](https://github.com/gakonst/foundry/blob/master/cli/src/cmd/build.rs#L200-L202) and always make it `true`, so that the user can't footgun

**Comment by onbjerg** [comment]
Wasn't entirely sure where to put the warning, so I ended up printing the warning on any build if `--no-auto-detect` is not passed. Thoughts? @gakonst

**Comment by onbjerg** [comment]
Why'd we merge this? It isn't working due to the above SSL error :smile:

**Pull request merged**
