### PR TITLE
Expand `forge test --match` interface

### PR DESCRIPTION
**Pull request by lattejed**
From issue: #227 

This PR deprecates `forge test --match` and expands the match interface to 

`--match-test`
`--no-match-test`
`--match-contract`
`--no-match-contract`

to allow for more granular test matching.

Internally, test runners have `Regex` replaced with `trait/impl TestFilter` to allow for custom matching logic in client code.

Conflicts have been added between `--match` and the new options to prevent mix/match of these. However, `--match` is effectively aliased to `--match-test` so there are no breaking changes.

Affected tests have been updated.

Any / all input welcome.

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
really great work - clean.

**Comment by lattejed** [comment]
Thanks @gakonst, appreciate it

**Comment by jo-es** [comment]
I'm in the process of migrating a larger dapptools project to foundry. We have separate repos for rpc based tests and local tests grouped by directory. `--match` from dapptools allows for specifying paths / sub directories to tests which works well in our case.

The only way to do this with forge atm would be to have an external script which generates a custom regex string and supply that to `--match-contract`.

To streamline this I would either extend `--match-contract` to account for the path to the contract file or add a new `--match-dir` / `--match-file` flag.

**Comment by gakonst** [comment]
@lattejed see above, nice idea

**Comment by lattejed** [comment]
I'll take a look at it

**Pull request merged**
