### PR TITLE
feat(verify): improve verify command

### LINKED ISSUE #932: Add forgetest for verify-contract
### Component

Forge, Cast

### Describe the feature you would like

test that verify-contract works with various inputs

### Additional context

https://github.com/gakonst/foundry/issues/931

### LINKED ISSUE #1012: verify-contract should verify as multi-file rather than flattening
### Component

Forge

### Describe the feature you would like

`forge verify-contract` currently flattens contracts for verification.
This removes:
* License information
* Import context

`forge verify-contract` example: https://rinkeby.etherscan.io/address/0x419aacdf7b24929a95f3ed87e8269743f2eeabaf#code

Remix multi-file verification example: https://rinkeby.etherscan.io/address/0x88262f5db936d54f8a6ab2994e049dbc7b0436b9#code

## License information
Solidity only allows one SPDX License identifier per file.  Flattening removes license information from the imported files.  

Worst case scenario, this could result in a more permissive license on an imported restrictive license library being used.  
Changing licenses on open source software is a bad outcome.

## Import context
Flattened files lose import context.  

It makes it more complex to quickly identify what is imported code and what is unique to the contract.  Especially for ERC20/ERC721 using common implementations from OpenZeppelin Contracts or solmate.

Tools like https://github.com/dethcrypto/ethereum-code-viewer#readme allow verified contracts to be opened in VS Code

Compare the rich information in multi-file verification from Remix: https://rinkeby.etherscan.deth.net/address/0x88262f5db936d54f8a6ab2994e049dbc7b0436b9#code with the flattened version from Foundry: https://rinkeby.etherscan.deth.net/address/0x419aacdf7b24929a95f3ed87e8269743f2eeabaf#code

## Additional
The two arguments I have come across for flattening is:
* Make auditing easier, compare deployed contracts (I hope open in VS Code resolves this)
* Make copypasta easier (I don't think this is a benefit or something we want to encourage)

### Additional context

_No response_

### LINKED ISSUE #1251: forge verify-contract should check that the contract is within the project `src` directory
### Component

Forge

### Describe the feature you would like

`verify-contract` does not check that the contract path argument is within the project's configured `src` directory. If the contract is outside that directory, it will fail with a misleading error.

Misleading error
```
Error: 
   0: Failed to get standard json input: cannot resolve file at ""/path/to/actual/contract/location/Contract.sol""
```

Instead, `verify_contract` should check that the path has the project `src` dir as a prefix, and inform the user if it is outside

Desired behavior:
```
Error:
   0: Contract "/path/to/actual/contract/location/Contract.sol" is outside of project source directory "/path/to/foundry/expected/src/
```

Note that the doubled `""...""` is due to escaped quotes in the underlying ethers-solc error message :)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #932 
Closes #1012
Closes #1251
Ref #1053

## Solution
- [x] support named chains ("mainnet", etc..)
- [x] compile flattened code locally to ensure it's valid
- [x] ~~add option for multi-file verification~~ added in #1242
- [ ] add integration tests

### CODE REVIEW

**Comment by gakonst** [comment]
https://github.com/gakonst/foundry/pull/1242 is merged, should be unblocked now

**Comment by mattsse** [comment]
integrated local dry run for flatten,
still needs some tests

**Review by gakonst — APPROVED** [review]
This LGTM, ideally we also want to autodetect compiler version (and append the `+commit....` stuff) and optimizer runs from the cache/output artifacts? Might also be good to think of how these should be further refactored to work with "forge deploy --verify" so we can "mass" verify an entire project's deployed contracts?

**Comment by mattsse** [comment]
> This LGTM, ideally we also want to autodetect compiler version (and append the `+commit....` stuff) and optimizer runs from the cache/output artifacts? Might also be good to think of how these should be further refactored to work with "forge deploy --verify" so we can "mass" verify an entire project's deployed contracts?

that makes sense, either as a sanity check or addiding the missing commit attribute

**Review by gakonst — APPROVED** [review]
let's follow up separately for other items, given urgency of fixes in this PR

**Pull request merged**
