### PR TITLE
feat/forge: add extra output types to config and CompilerArgs on build

### PR DESCRIPTION
**Pull request by joshieDo**
## Motivation
ref #611 
It prints into `out/Contract.sol/` the requested output type[s].

~~Requires PR: https://github.com/gakonst/ethers-rs/pull/847~~

---
Usage:

foundry.toml:
```
[default]
optimizer = true
optimizer_runs = 1_000_000
extra_output = ["ir", "ewasm", "irOptimized", "evm.assembly"]
```
or
```
forge build --extra-output evm.assembly --extra-output ir --extra-output irOptimized --extra-output ewasm
```

`$ ls out/C.sol/`
```
C.asm  C.ewasm  C.ir  C.iropt  C.json  ERC20.asm  ERC20.ewasm  ERC20.ir  ERC20.iropt  ERC20.json  VM.asm  VM.ewasm  VM.ir  VM.iropt  VM.json
```

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
I very much like this direction, this is way better than my attempts to make `solc_config` work in the `Config`.

Think we can deprecate the `solc_config` field then

have to think about the ethers-rs PR,

**Review by gakonst — APPROVED** [review]
looking good

**Comment by brockelmore** [comment]
@mattsse we do need to enable the removal of ipfs hash and what not thought fwiw so should consider how we want to approach that as well

**Comment by gakonst** [comment]
yeah anything that we can do to avoid the bytecode hash changing based on paths or w/e should be added, i'd go as far and say as a default

**Pull request merged**
