### PR TITLE
fix cast send argument parsing

### PR DESCRIPTION
**Pull request by calldata**

### CODE REVIEW

**Comment by calldata** [comment]
fix #630 

my local test
image

**Review by mattsse — CHANGES_REQUESTED** [review]
thanks!

mind moving the function to utils.rs?

**Comment by joshieDo** [comment]
For the `gas` and `value` maybe we can use the token parsing used for example on `--to-unit`?  Would allow us to use `1ether` or `1gwei`

https://github.com/gakonst/foundry/blob/dd76c0f05c72c66b3ae67ea0a298e6ed9cc246bd/cast/src/lib.rs#L902

**Comment by mattsse** [comment]
> For the `value` field maybe we can use the token parsing used for example on `--to-unit`? Would allow us to use stuff like `1ether`, `1gwei` or `0.1ether`
> 
> https://github.com/gakonst/foundry/blob/dd76c0f05c72c66b3ae67ea0a298e6ed9cc246bd/cast/src/lib.rs#L902

great idea!

not sure if 

https://github.com/rust-ethereum/ethabi/blob/c622438f9fd2ac2f9b3c38ecb1ca760c069d9ec2/ethabi/src/token/lenient.rs#L44

strips the `0x`, so we'd need some tests,

@calldata would you like to take this on?

**Comment by calldata** [comment]
That's ok. Time to bed now

**Comment by gakonst** [comment]
nice work, let's merge this as-is given it fixes the issue, and we can expand the formatting to use the new `1ether`-style strings separately as a `feature` PR

**Pull request merged**
