### PR TITLE
ci: matrix builds

### PR DESCRIPTION
**Pull request by mattsse**
build on various targets

### CODE REVIEW

**Comment by gakonst** [comment]
blocked on https://github.com/gakonst/ethers-rs/pull/682 / https://github.com/roynalnaruto/svm-rs/pull/9

**Comment by mattsse** [comment]
openssl probably needs some manual help finding the pkg config path: https://docs.rs/openssl/latest/openssl/#manual
also not sure if we need or could even ship for all those targets

**Comment by gakonst** [comment]
Yeah agreed, I'd trim the targets down

**Comment by gakonst** [comment]
Looks like there's some SVM issue now?  cc @roynalnaruto 

```
thread 'sputnik::cheatcodes::cheatcode_handler::tests::cheatcodes' panicked at 'called `Result::unwrap()` on an `Err` value: Io(SolcIoError { io: Os { code: 193, kind: Uncategorized, message: "%1 is not a valid Win32 application." }, path: "C:\\Users\\runneradmin\\.svm\\0.6.12\\solc-0.6.12" })', evm-adapters\src\lib.rs:198:37
```

**Comment by gakonst** [comment]
superseded by #244

**Pull request closed without merging**
