### PR TITLE
perf(forge): improve workspace path autodection

### PR DESCRIPTION
**Pull request by mattsse**
## Changes

* move TryFrom<BuildArgs> to separate function
* add `--hardhat` flag as shortcut for `--contracts contracts --lib-paths node_modules`
* autodetect workspace layout:
* dapptools style takes precedent, but if `src` / `out` are missing, check for `contracts` and `artifacts` as well

### CODE REVIEW

**Comment by transmissions11** [comment]
> dapptools style takes precedent, but if src / out are missing, check for contracts and artifacts as well

what if they just cloned a dapptools repo fresh from git? it won't have out but still have src

**Comment by mattsse** [comment]
> > dapptools style takes precedent, but if src / out are missing, check for contracts and artifacts as well
> 
> what if they just cloned a dapptools repo fresh from git? it won't have out but still have src

in that case `out` will also be set, dapptools style is always checked first and is always the fallback if `contracts`/`artifacts` also does not exist, but perhaps these assumptions are not always the expected behavior?

**Comment by transmissions11** [comment]
@mattsse my bad i meant `out`. it won't be set on a fresh clone as most ppl git ignore it.

**Comment by mattsse** [comment]
> @mattsse my bad i meant `out`. it won't be set on a fresh clone as most ppl git ignore it.

it follows this logic

https://github.com/gakonst/foundry/pull/217/files#diff-399b0ef06f74fce04b5cefda9641dea0e2cb8f4ec03cad45020dba2916a7f971R102-R116

so basically it will always use `out` unless `artifacts` exist already

**Review by gakonst — APPROVED** [review]
great UX upgrade

**Pull request merged**
