### PR TITLE
feat(forge): add tree command

### PR DESCRIPTION
**Pull request by mattsse**
~~**BLOCKED BY** https://github.com/gakonst/ethers-rs/pull/933~~

## Motivation
add `forge tree`

### CODE REVIEW

**Comment by gakonst** [comment]
There is some bug with subtree alignment, see `forge tree --no-dedupe` for https://github.com/gakonst/dapptools-template

telegram-cloud-photo-size-2-5226437843444939478-y

**Comment by gakonst** [comment]
Yes exactly @mattsse it's the branches under src/Greeter.sol, which appear twice 

The other one that seems wrong is the one below Greeter.t.sol, doesn't seem like it should have the little leg, and should just be a |_?
image

**Comment by mattsse** [comment]
Ref https://github.com/gakonst/ethers-rs/pull/999

**Review by gakonst — APPROVED** [review]
bumped ethers, tested with a couple repos, lgtm

**Pull request merged**
