### PR TITLE
WIP: fixing etherscan verify

### PR DESCRIPTION
**Pull request by gakonst**
Depends on https://github.com/gakonst/ethers-rs/pull/755. Does not work yet, because it requires us supporting file flattening or multiple files on `ethers-etherscan`.

Etherscan verification as-is right now is completely broken

### CODE REVIEW

**Comment by gakonst** [comment]
Should be able to make progress here once https://github.com/gakonst/ethers-rs/pull/774 is merged

**Comment by tarrencev** [comment]
@gakonst anything i can help with on here?

**Comment by gakonst** [comment]
I'd coordinate with @rkrasiuk who's been on top of it on ethers-rs flattening

**Comment by tarrencev** [comment]
> @tarrencev here is the way we are moving forward:
> 
> 1. we need to merge [Change artifact naming conventions #809](https://github.com/gakonst/ethers-rs/pull/809)
> 2. [fix/etherscan verification #828](https://github.com/gakonst/ethers-rs/pull/828) uses the results of prev PR to pick up compiler version and num of optimizations
> 3. and then we can make some progress on this PR

sweet! let me know if there is anything i can help with

**Comment by gakonst** [comment]
@rkrasiuk the ethers PR is merged and as discussed we can do the auto version/opti runs detection after @mattsse's cache PR is merged. 

Up to you if you wanna continue from this PR, or start fresh and maybe cherry pick any relevant code you find useful?

Very excited to get this over the line..

**Comment by rkrasiuk** [comment]
@gakonst sounds good. i'd def cherry pick some changes from this PR. excited as well!

**Pull request closed without merging**
