### PR TITLE
test: update integration tests to new output

### PR DESCRIPTION
**Pull request by onbjerg**
Updates an integration test to the new `forge test` output

### CODE REVIEW

**Comment by onbjerg** [comment]
Hold on merge

**Comment by onbjerg** [comment]
Rebased

**Review by mattsse — APPROVED** [review]
lgtm,
how best to proceed to strip the root.

there are some problems with tempdirs which can be symlinks

**Comment by onbjerg** [comment]
> lgtm, how best to proceed to strip the root.
> 
> there are some problems with tempdirs which can be symlinks

Not entirely sure, we strip it using the `find_project_root` func from `config` crate - maybe it can't find the root?

**Comment by mattsse** [comment]
hmm, could be a symlink tempdir thing, that burned me already quite a bit, on mac for example tempdirs are symlinked so after `canonicalize` they are totally different...

**Pull request merged**
